workflow:
  rules:
    - when: manual

stages:
  - test

e2e_pytest:
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip

  before_script:
    - $ErrorActionPreference = "Stop"
    - New-Item -ItemType Directory -Force -Path artifacts | Out-Null
    - New-Item -ItemType Directory -Force -Path artifacts\reports | Out-Null
    - New-Item -ItemType Directory -Force -Path artifacts\logs | Out-Null
    - New-Item -ItemType Directory -Force -Path artifacts\screenshots | Out-Null
    - py -3 --version
    - py -3 -m venv .venv
    - .\.venv\Scripts\python -m pip install --upgrade pip
    - .\.venv\Scripts\python -m pip install -r requirements.txt
    - .\.venv\Scripts\python -m pip install pytest-html

  script:
    - .\.venv\Scripts\python -m pytest .\tests --headless --junitxml=artifacts/reports/junit.xml

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - artifacts/reports/
      - artifacts/logs/
      - artifacts/screenshots/
    reports:
      junit: artifacts/reports/junit.xml
